"""
03-simulate-residence.py

This script is a failure and doesn't work.

Purpose
This script performs weekly “instantaneous injection” particle experiments for each reef and year using the 
pre-downloaded subcubes. Particles are seeded uniformly within the reef polygon once per week at a fixed local 
time. Particles are advected by surface currents with optional horizontal diffusion. Particles are not deleted 
when they leave the reef polygon. Instead, at each daily output the script records how many particles are inside 
the reef, which represents the remaining concentration relative to the initial injection. Particles are deleted 
only when they leave a slightly shrunken modelling envelope near the edge of the subcube to avoid edge recirculation. 
The main outputs are weekly survival curves and a threshold-based residence time, for example the time to 10 
percent remaining. An MP4 animation is produced for visual debugging.

Inputs
Local NetCDF subcubes generated by the extraction stage, each containing u, v, longitude, latitude, zc and 
time at a single depth and covering a rectangular i-j window. A reef polygon layer with LABEL_ID and GBR_NAME 
identical to the extraction stage. The LABEL_IDs determine which subcubes to process. The default weekly start 
is Monday at 12:00 local time in Australia/Brisbane, with the timezone removed before passing times to Parcels.

Core behaviour
For each reef and year the script opens the corresponding subcube and constructs a Parcels FieldSet with 
mesh="spherical". Two constant fields named Kh_zonal and Kh_meridional provide uniform horizontal diffusivity 
if a positive Kh is given. A binary ReefMask field is created by rasterising the reef polygon onto the 
subcube’s lon/lat grid, with values 1 inside the polygon and 0 outside. A DomainMask is created with ones 
everywhere except for a user-specified number of cells that are set to zero along the outer edges. Particles 
are seeded uniformly over the polygon interior using rejection sampling in the polygon’s bounding box. 
The kernels are RK4 advection, optional DiffusionUniformKh, a kernel that sets a per-particle inside flag 
by sampling ReefMask at the output times, and a kernel that deletes particles when they encounter DomainMask 
equal to zero. Particles are not deleted upon leaving ReefMask. The execution uses a five minute timestep, a 
daily output interval, and a runtime of 21 days unless otherwise specified.

Outputs
For each weekly injection the script writes a Parcels ParticleFile NetCDF with daily inside flags for each 
particle. It then reads the file to compute the number and fraction of particles inside the reef at each 
daily output. The fraction starts at one and typically decays due to advection and diffusion. The threshold-based 
residence time tau10 is defined as the first time when the inside fraction is less than or equal to 0.10. Weekly 
results are appended to a CSV with columns gbr_name, label_id, week_start, n, tau10_days, days and frac_remaining. 
The script also renders an MP4 animation for at least the first weekly run of each year showing the reef outline, 
the modelling domain and particle positions through time for quick visual diagnostics. All outputs are written 
under runs/LABEL_ID/YEAR/ by default, with filenames that include GBR_NAME and LABEL_ID.

Assumptions and constraints
The simulation is two-dimensional at a single depth. Use depth index k=40 from the subcube, which is near 
-2.5 m. Vertical velocity and vertical diffusion are not used. The concentration proxy is the fraction of 
particles inside the reef polygon at discrete daily times. If no particles cross the 10 percent threshold 
during the 21 day window, tau10_days is recorded as NaN for that week. The modelling envelope can be trimmed 
by one or more cells to avoid artificial accumulation along the very edge of the subcube. Time handling uses 
naive datetimes when calling Parcels but weekly start times are generated in Australia/Brisbane then converted 
to naive to match the dataset’s AEST axis.

Command line interface
Provide arguments for --reef-shp, --ids, --years, --subcube-dir, --weekly-start-day (defaults to MON), --injection-hour (defaults to 12), --particles (defaults to 3000), --runtime-days (defaults to 21), --kh (defaults to 10 m^2 s^-1), --edge-shrink-cells (defaults to 1), --outdir and --seed for reproducibility. Accept --threshold to allow values other than 0.10. The script should log the chosen parameters, the number of particles per injection and the computed tau10 for each week.

Performance and robustness
Create one FieldSet per reef per year and reuse it across weekly runs. Write outputs incrementally so a long run can be resumed. Use Parcels recovery handlers to delete particles that attempt to move out of time range or domain. Guard against missing subcubes and mismatched LABEL_IDs. Permit a --preview option that simulates a single week for one reef to validate the setup quickly on a laptop.

Example
python 03-simulate-residence.py --reef-shp reefs.shp --ids 16-068 18-032 18-096 19-019 --years 2019 --subcube-dir data/subcubes --particles 3000 --kh 10 --runtime-days 21 --edge-shrink-cells 1 --outdir runs
"""

from __future__ import annotations

import argparse
import logging
import sys
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

import geopandas as gpd
import pandas as pd
import numpy as np
import xarray as xr
from shapely.geometry import Polygon, Point, MultiPolygon
from shapely.ops import unary_union

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

try:
    from parcels import FieldSet  # type: ignore
except ImportError:  # pragma: no cover
    FieldSet = None  # type: ignore


# --------------------------------------------------------------------------------------
# Logging utilities
# --------------------------------------------------------------------------------------


def configure_logging(log_file: Path | None = None) -> None:
    if logging.getLogger().handlers:
        return
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    fmt = logging.Formatter(
        fmt="% (asctime)s | % (levelname)s | % (message)s".replace('% ', '%'),
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    sh = logging.StreamHandler(sys.stdout)
    sh.setFormatter(fmt)
    root.addHandler(sh)
    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        fh = logging.FileHandler(log_file, mode="a", encoding="utf-8")
        fh.setFormatter(fmt)
        root.addHandler(fh)

def weekly_injections(year: int, injection_hour: int) -> List[np.datetime64]:
	"""Return list of weekly injection datetimes starting 1 Jan of year.

	Each injection is at local (naive) hour every 7 days until year end.
	"""
	if not (0 <= injection_hour <= 23):
		raise ValueError("injection_hour must be between 0 and 23 inclusive")
	start = np.datetime64(f"{year}-01-01T{injection_hour:02d}:00:00")
	end_limit = np.datetime64(f"{year}-12-31T23:59:59")
	weeks: List[np.datetime64] = []
	current = start
	one_week = np.timedelta64(7, "D")
	while current <= end_limit:
		weeks.append(current)
		current = current + one_week
	return weeks

def required_day_strings(start: np.datetime64, runtime_days: int) -> List[str]:
	"""Return list of YYYY-MM-DD day strings needed from start for runtime.

	Includes the start day and all full subsequent days up to start + runtime_days.
	Example: runtime_days=21 returns 22 calendar days (0..21) to ensure coverage.
	"""

	days: List[str] = []
	base_day = start.astype("datetime64[D]")
	for d in range(runtime_days + 1):
		day = base_day + np.timedelta64(d, "D")
		days.append(str(day))
	return days


# --------------------------------------------------------------------------------------
# File discovery & coverage checks
# --------------------------------------------------------------------------------------


def list_daily_subcubes(subcube_dir: Path, label_id: str, year: int) -> List[Path]:
	"""List daily subcube NetCDF files for a given reef-year.

	Expected layout produced by extraction stage:
	subcube_dir / LABEL_ID / YEAR / <name>_<LABEL_ID>_k<k>_YYYYMMDD.nc
	"""

	year_dir = subcube_dir / label_id / str(year)
	if not year_dir.exists():
		return []
	# Broad match then filter: we expect final underscore-separated token to be an 8-digit date YYYYMMDD
	candidates = list(year_dir.glob(f"*_{label_id}_k*_{year}*.nc"))
	results: List[Path] = []
	for p in candidates:
		stem = p.stem
		parts = stem.split("_")
		if not parts:
			continue
		date_token = parts[-1]
		if len(date_token) == 8 and date_token.isdigit() and date_token.startswith(str(year)):
			results.append(p)
	return sorted(results)
def available_day_index(files: List[Path]) -> dict[str, Path]:
	"""Map YYYYMMDD -> file Path for quick lookup."""

	index: dict[str, Path] = {}
	for f in files:
		# Extract trailing date stamp before extension
		stem = f.stem  # ..._YYYYMMDD
		parts = stem.split("_")
		if not parts:
			continue
		last = parts[-1]
		if len(last) == 8 and last.isdigit():
			index[last] = f
	return index


def verify_coverage(
	label_id: str,
	year: int,
	injection_times: List[np.datetime64],
	runtime_days: int,
	day_index: dict[str, Path],
) -> List[str]:
	"""Verify all required day files exist for each weekly injection.

	Returns a sorted list of missing YYYY-MM-DD strings (unique across weeks).
	"""

	missing: set[str] = set()
	for inj in injection_times:
		needed = required_day_strings(inj, runtime_days)
		for d in needed:
			ymd = d.replace("-", "")
			if ymd not in day_index:
				missing.add(d)
	return sorted(missing)


# --------------------------------------------------------------------------------------
# FieldSet preparation
# --------------------------------------------------------------------------------------


def fieldset_from_daily_files(files: List[Path]):  # type: ignore[no-untyped-def]
	"""Create a Parcels FieldSet from a list of daily NetCDF files.

	Parameters
	----------
	files : list[Path]
		Ordered list of daily files spanning required period.
	"""

	if FieldSet is None:  # pragma: no cover
		raise ImportError("parcels is not installed; cannot build FieldSet")
	if not files:
		raise ValueError("No files supplied for FieldSet construction")
	filenames = {"U": [str(f) for f in files], "V": [str(f) for f in files]}
	variables = {"U": "u", "V": "v"}
	dimensions = {"U": {"time": "time", "lat": "latitude", "lon": "longitude"},
				  "V": {"time": "time", "lat": "latitude", "lon": "longitude"}}
	logging.info("Building FieldSet from %d daily files", len(files))
	return FieldSet.from_netcdf(filenames, variables, dimensions, mesh="spherical")


# --------------------------------------------------------------------------------------
# Mask construction & sampling utilities (Stage 2 additions)
# --------------------------------------------------------------------------------------


def polygon_to_mask_field(fs, polygon: Polygon, name: str = "ReefMask"):  # type: ignore[no-untyped-def]
	"""Create a binary mask Field (1 inside polygon, 0 outside) on FieldSet grid.

	Uses shapely.vectorized.contains when available for speed; otherwise
	falls back to prepared geometry point iteration.
	"""
	try:
		from parcels import Field  # type: ignore
	except ImportError:  # pragma: no cover
		raise
	lon = fs.U.grid.lon
	lat = fs.U.grid.lat
	# Attempt fast vectorized path
	mask_bool: np.ndarray
	try:
		# Preferred in shapely >=2
		from shapely import contains_xy  # type: ignore
		mask_bool = contains_xy(polygon, lon, lat)
	except Exception:  # noqa: BLE001
		# Try deprecated vectorized.contains
		try:  # pragma: no cover
			from shapely import vectorized  # type: ignore
			mask_bool = vectorized.contains(polygon, lon, lat)
		except Exception:
			# Fallback: prepared geometry loop (slower)
			try:
				from shapely.prepared import prep  # type: ignore
				P = prep(polygon)
			except Exception:  # noqa: BLE001
				P = polygon  # type: ignore
			mask_bool = np.zeros(lon.shape, dtype=bool)
			for j in range(lon.shape[0]):
				for i in range(lon.shape[1]):
					if P.contains(Point(float(lon[j, i]), float(lat[j, i]))):
						mask_bool[j, i] = True
	mesh_arg = getattr(getattr(fs.U, "grid", None), "mesh", "spherical")
	mask = mask_bool.astype(np.float32)
	field = Field(name=name, data=mask, lon=lon, lat=lat, mesh=mesh_arg)
	fs.add_field(field)
	return field


def add_domain_mask(fs, shrink: int, name: str = "DomainMask"):  # type: ignore[no-untyped-def]
	"""Add a DomainMask field with zeros on shrunken outer rim.

	Parameters
	----------
	fs : FieldSet
	shrink : int
		Number of outer cells (per side) to flag as 0 (excluded). 0 keeps all ones.
	name : str
		Field name.
	"""
	if shrink < 0:
		raise ValueError("shrink must be >= 0")
	try:
		from parcels import Field  # type: ignore
	except ImportError:  # pragma: no cover
		raise
	lon = fs.U.grid.lon
	shape = lon.shape
	mask = np.ones(shape, dtype=np.float32)
	if shrink > 0:
		mask[:shrink, :] = 0
		mask[-shrink:, :] = 0
		mask[:, :shrink] = 0
		mask[:, -shrink:] = 0
	mesh_arg = getattr(getattr(fs.U, "grid", None), "mesh", "spherical")
	field = Field(name=name, data=mask, lon=lon, lat=fs.U.grid.lat, mesh=mesh_arg)
	fs.add_field(field)
	return field


def sample_points_in_polygon(polygon: Polygon | MultiPolygon, n: int, seed: int | None = None) -> Tuple[np.ndarray, np.ndarray]:
	"""Uniformly sample n points inside (Multi)Polygon via rejection sampling.

	Uses simple bbox rejection. For complex geometries a more advanced spatial
	sampling could be substituted later.
	"""
	if isinstance(polygon, MultiPolygon):  # unify to single geometry
		polygon = unary_union(polygon)
	from shapely.prepared import prep  # type: ignore
	prepared = prep(polygon)
	rng = np.random.default_rng(seed)
	minx, miny, maxx, maxy = polygon.bounds
	lons: list[float] = []
	lats: list[float] = []
	tries = 0
	max_tries = n * 100
	while len(lons) < n and tries < max_tries:
		tries += 1
		x = rng.uniform(minx, maxx)
		y = rng.uniform(miny, maxy)
		if prepared.contains(Point(float(x), float(y))):
			lons.append(x)
			lats.append(y)
	if len(lons) < n:
		raise RuntimeError(f"Could not sample {n} points inside polygon after {tries} tries")
	return np.array(lons, dtype=np.float32), np.array(lats, dtype=np.float32)


# --------------------------------------------------------------------------------------
# Particle class & kernels
# --------------------------------------------------------------------------------------


def _install_particle_kernels():  # type: ignore[no-untyped-def]
	try:
		from parcels import JITParticle, Variable  # type: ignore
	except ImportError:  # pragma: no cover
		return None

	class ReefParticle(JITParticle):  # type: ignore
		inside = Variable('inside', dtype=np.int32, initial=0)  # 1 if inside reef mask at sample time
		active = Variable('active', dtype=np.int32, initial=1)  # 1 while not deleted by domain mask

	def SampleInside(particle, fieldset, time):  # type: ignore[no-untyped-def]
		# Sample reef and domain masks; inside only if reef==1 and active domain.
		# Avoid bare return (older Parcels JIT had issues when compiling kernels with bare return statements).
		reef = fieldset.ReefMask[time, particle.depth, particle.lat, particle.lon]
		domain = fieldset.DomainMask[time, particle.depth, particle.lat, particle.lon]
		if domain < 0.5:
			particle.active = 0
			particle.delete()
		else:
			if reef >= 0.5:
				particle.inside = 1
			else:
				particle.inside = 0

	return ReefParticle, SampleInside


def _add_diffusivity_fields(fs, kh: float):  # type: ignore[no-untyped-def]
	if kh <= 0:
		return
	try:
		from parcels import Field  # type: ignore
	except ImportError:  # pragma: no cover
		raise
	lon = fs.U.grid.lon
	lat = fs.U.grid.lat
	shape = lon.shape
	data = np.full(shape, kh, dtype=np.float32)
	mesh_arg = getattr(getattr(fs.U, "grid", None), "mesh", "spherical")
	fs.add_field(Field(name="Kh_zonal", data=data, lon=lon, lat=lat, mesh=mesh_arg))
	fs.add_field(Field(name="Kh_meridional", data=data, lon=lon, lat=lat, mesh=mesh_arg))


def _sanitize(name: str) -> str:
	return "".join(c.lower() if c.isalnum() else "_" for c in name).strip("_")


def _expected_sample_hours(runtime_days: int, interval_hours: float) -> List[float]:
	runtime_hours = runtime_days * 24.0
	values: List[float] = []
	h = 0.0
	while h <= runtime_hours + 1e-6:  # numeric tolerance
		values.append(round(h, 6))
		h += interval_hours
	return values


def _load_existing_csv(path: Path) -> pd.DataFrame:
	if not path.exists():
		return pd.DataFrame()
	try:
		df = pd.read_csv(path)
		return df
	except Exception:  # noqa: BLE001
		return pd.DataFrame()


def _csv_week_complete(df: pd.DataFrame, week_start: str, expected_last_hour: float) -> bool:
	if df.empty:
		return False
	grp = df[df["week_start"] == week_start]
	if grp.empty:
		return False
	# Check presence of final expected hour_from_release
	return any(abs(grp["hour_from_release"].values - expected_last_hour) < 1e-6)


def _remove_week(df: pd.DataFrame, week_start: str) -> pd.DataFrame:
	if df.empty:
		return df
	return df[df["week_start"] != week_start].copy()


def _debug_parcels_imports():
	"""Print detailed diagnostics for Parcels component availability."""
	components = [
		("parcels", "Root package"),
		("parcels.particleset", "ParticleSet module"),
		("parcels.tools.error", "ErrorCode module"),
		("parcels.kernel", "Kernel module"),
	]
	for mod, desc in components:
		try:
			__import__(mod)
			logging.info("[parcels debug] OK: %s (%s)", mod, desc)
		except Exception as e:  # noqa: BLE001
			logging.error("[parcels debug] FAIL: %s (%s): %s", mod, desc, e)
	# Check installed version
	try:
		import parcels  # type: ignore
		logging.info("[parcels debug] parcels version: %s", getattr(parcels, '__version__', 'unknown'))
	except Exception:
		pass


def animate_week(pf_path: Path, reef_polygon: Polygon, out_path: Path, max_hours: float = 168.0):
	"""Create MP4 animation for first week using particle file outputs.

	Parameters
	----------
	pf_path : Path
		ParticleFile NetCDF path.
	reef_polygon : Polygon
		Reef outline for plotting.
	out_path : Path
		MP4 output path.
	max_hours : float
		Limit animation to this many hours from release (default 7 days).
	"""
	import matplotlib.pyplot as plt  # type: ignore
	from matplotlib import animation  # type: ignore
	ds = xr.open_dataset(pf_path)
	if "lon" not in ds or "lat" not in ds:
		logging.warning("Particle file missing lon/lat for animation")
		return
	lon = ds["lon"].values  # (obs, traj)
	lat = ds["lat"].values
	times = ds["time"].values
	base_time = np.datetime64(times[0])
	elapsed_hours = ((times - base_time).astype("timedelta64[s]").astype(float) / 3600.0)
	valid_frames = np.where(elapsed_hours <= max_hours)[0]
	if valid_frames.size == 0:
		logging.warning("No frames within max_hours for animation")
		return
	valid_frames = valid_frames.tolist()
	fig, ax = plt.subplots(figsize=(5, 5))
	minx, miny, maxx, maxy = reef_polygon.bounds
	padx = (maxx - minx) * 0.2
	pady = (maxy - miny) * 0.2
	ax.set_xlim(minx - padx, maxx + padx)
	ax.set_ylim(miny - pady, maxy + pady)
	reef_x, reef_y = reef_polygon.exterior.xy
	ax.plot(reef_x, reef_y, color='darkgreen', linewidth=1.2)
	scat = ax.scatter([], [], s=4, c='tab:blue')
	ax.set_title("Week animation")
	def init():  # noqa: D401
		scat.set_offsets(np.empty((0, 2)))
		return (scat,)
	def update(frame_index):
		f = valid_frames[frame_index]
		pts = np.column_stack([lon[f, :], lat[f, :]])
		scat.set_offsets(pts)
		ax.set_title(f"t = {elapsed_hours[f]:.1f} h, n = {np.isfinite(pts[:,0]).sum()}")
		return (scat,)
	anim = animation.FuncAnimation(fig, update, init_func=init, frames=len(valid_frames), blit=True, interval=100)
	out_path.parent.mkdir(parents=True, exist_ok=True)
	try:
		anim.save(out_path, fps=12, dpi=150)
		logging.info("Animation written: %s", out_path)
	except Exception as e:  # noqa: BLE001
		logging.warning("Animation failed: %s", e)
	plt.close(fig)


# --------------------------------------------------------------------------------------
# CLI and main flow (Stage 1 only)
# --------------------------------------------------------------------------------------


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
	p = argparse.ArgumentParser(
		description="Weekly particle residence simulations over reef subcubes (build FieldSet, run injections, output CSV + optional animation)",
		formatter_class=argparse.ArgumentDefaultsHelpFormatter,
	)
	p.add_argument(
		"--reef-shp",
		type=Path,
		default=Path(
			"data/in-3p/GBR_AIMS_Complete-GBR-feat_V1b/TS_AIMS_NESP_Torres_Strait_Features_V1b_with_GBR_Features.shp"
		),
		help="Path to reef shapefile (.shp) or GeoPackage (.gpkg).",
	)
	p.add_argument("--ids", nargs="+", required=True, help="One or more LABEL_ID values to process. Space separated")
	p.add_argument(
		"--years",
		nargs="+",
		type=int,
		required=True,
		help="Year or list of years; if two numbers given treat as inclusive range.",
	)
	p.add_argument(
		"--subcube-dir",
		type=Path,
		default=Path("working/02"),
		help="Root directory containing daily extraction outputs.",
	)
	p.add_argument(
		"--injection-hour", type=int, default=12, help="Hour of day (0-23) for weekly injections starting 1 Jan."
	)
	p.add_argument(
		"--runtime-days", type=int, default=21, help="Runtime length in days for each weekly simulation (also used for coverage check)."
	)
	p.add_argument(
		"--weeks",
		nargs="*",
		type=int,
		default=None,
		help="Optional zero-based week indices to process within each year (after 1 Jan start). Useful for debugging.",
	)
	p.add_argument(
		"--preview",
		action="store_true",
		help="Preview mode: only first reef, first year, first week is simulated (fast diagnostic).",
	)
	p.add_argument("--particles", type=int, default=3000, help="Number of particles per weekly injection")
	p.add_argument("--kh", type=float, default=10.0, help="Horizontal diffusivity Kh (m^2 s^-1); 0 disables diffusion")
	p.add_argument(
		"--edge-shrink-cells",
		type=int,
		default=1,
		help="Number of outer grid cells to exclude via DomainMask (0 keeps full window)",
	)
	p.add_argument(
		"--output-interval-hours",
		type=float,
		default=3.0,
		help="Sampling/output interval in hours for computing inside fractions (CSV granularity)",
	)
	p.add_argument(
		"--outdir",
		type=Path,
		default=Path("working/03"),
		help="Root directory for simulation outputs (CSV, ParticleFiles, animations)",
	)
	p.add_argument("--seed", type=int, default=42, help="Base random seed for reproducibility")
	p.add_argument(
		"--animate",
		action="store_true",
		help="Generate MP4 animation for first simulated week of each reef-year",
	)
	p.add_argument(
		"--threshold",
		type=float,
		default=0.10,
		help="Inside fraction threshold for tau10-style metrics (recorded though tau10 may be deferred)",
	)
	p.add_argument(
		"--debug-imports",
		action="store_true",
		help="Log detailed diagnostics about Parcels imports if components are missing",
	)
	p.add_argument(
		"--debug-particles",
		action="store_true",
		help="Log detailed particle array diagnostics before ParticleSet creation",
	)
	p.add_argument(
		"--log-file", type=Path, default=None, help="Optional log file path for batch/HPC runs."
	)
	return p.parse_args(argv)


def _years_list(year_args: List[int]) -> List[int]:
	if len(year_args) == 1:
		return year_args
	if len(year_args) == 2:
		a, b = year_args
		if a > b:
			a, b = b, a
		return list(range(a, b + 1))
	return sorted(set(year_args))


def load_reef_polygons(path: Path, ids: List[str]) -> gpd.GeoDataFrame:
	gdf = gpd.read_file(path)
	required = {"LABEL_ID", "GBR_NAME"}
	missing = required - set(gdf.columns)
	if missing:
		raise ValueError(f"Reef file missing required columns: {missing}")
	subset = gdf[gdf["LABEL_ID"].isin(ids)].copy()
	if subset.empty or subset["LABEL_ID"].nunique() != len(set(ids)):
		present = set(subset["LABEL_ID"].unique())
		miss = [i for i in ids if i not in present]
		raise ValueError(f"Requested LABEL_ID values not found: {miss}")
	subset["_order"] = subset["LABEL_ID"].apply(lambda v: ids.index(v))
	return subset.sort_values("_order")


def main(argv: Sequence[str] | None = None) -> int:
	args = parse_args(argv)
	configure_logging(args.log_file)
	logging.info("Simulate-residence start")

	try:
		reefs = load_reef_polygons(args.reef_shp, args.ids)
	except Exception as e:  # noqa: BLE001
		logging.error("Failed loading reef polygons: %s", e)
		return 2

	years = _years_list(args.years)
	logging.info("Years: %s", years)

	total_fieldsets = 0
	for rid, row in reefs.groupby("LABEL_ID"):
		gbr_name = row.iloc[0]["GBR_NAME"]
		logging.info("Reef %s (%s)", rid, gbr_name)
		for year in years:
			daily_files = list_daily_subcubes(args.subcube_dir, rid, year)
			if not daily_files:
				logging.error("No daily files found for %s %d", rid, year)
				return 3
			day_index = available_day_index(daily_files)
			injections = weekly_injections(year, args.injection_hour)
			if args.weeks:
				injections = [injections[w] for w in args.weeks if 0 <= w < len(injections)]
			if args.preview:
				injections = injections[:1]
			missing = verify_coverage(rid, year, injections, args.runtime_days, day_index)
			if missing:
				logging.error("Missing %d day files for %s %d (e.g. %s)", len(missing), rid, year, ", ".join(missing[:5]))
				return 4
			# Build FieldSet for first injection window (reused across weeks)
			needed_days = required_day_strings(injections[0], args.runtime_days)
			needed_files = [day_index[d.replace('-', '')] for d in needed_days]
			try:
				fs = fieldset_from_daily_files(needed_files)
			except Exception as e:  # noqa: BLE001
				logging.error("FieldSet build failed %s %d: %s", rid, year, e)
				return 5
			# Build masks for this reef
			# Combine geometries (union_all preferred over deprecated unary_union)
			reef_geom = row.geometry.union_all() if hasattr(row.geometry, "union_all") else row.geometry.unary_union
			polygon_to_mask_field(fs, reef_geom, name="ReefMask")
			add_domain_mask(fs, args.edge_shrink_cells, name="DomainMask")
			_add_diffusivity_fields(fs, args.kh)
			ReefParticle, SampleInside = _install_particle_kernels()  # type: ignore
			if ReefParticle is None:  # pragma: no cover
				logging.error("parcels not installed; cannot simulate")
				return 8
			try:
				from parcels import (  # type: ignore
					ParticleSet,
					AdvectionRK4,
					DiffusionUniformKh,
				)
			except ImportError as e:  # pragma: no cover
				logging.error("parcels core components missing: %s", e)
				if args.debug_imports:
					_debug_parcels_imports()
				return 8
			# Attempt to import ErrorCode; create fallback if absent
			try:
				from parcels import ErrorCode  # type: ignore
			except Exception:  # noqa: BLE001
				class ErrorCode:  # type: ignore
					ErrorOutOfBounds = "ErrorOutOfBounds"
					ErrorThroughSurface = "ErrorThroughSurface"
					ErrorTimeExtrapolation = "ErrorTimeExtrapolation"
				logging.warning("Proceeding with fallback ErrorCode definitions (installed Parcels lacks ErrorCode)")
			# CSV setup
			csv_dir = args.outdir / rid / str(year)
			csv_dir.mkdir(parents=True, exist_ok=True)
			csv_path = csv_dir / f"{_sanitize(gbr_name)}_{rid}_weekly.csv"
			existing = _load_existing_csv(csv_path)
			expected_hours = _expected_sample_hours(args.runtime_days, args.output_interval_hours)
			final_hour = expected_hours[-1]
			# Per-week rows accumulated and appended to existing dataframe
			for w_index, inj_time in enumerate(injections):
				week_str = str(inj_time).replace(" ", "T")
				# Resume check
				if _csv_week_complete(existing, week_str, final_hour):
					logging.info("Skip week %s already complete (%s %d)", week_str, rid, year)
					continue
				elif not existing.empty:
					# Remove partial entries so we overwrite
					existing = _remove_week(existing, week_str)
				# Seed particles uniformly
				seed_val = args.seed + year * 100 + w_index
				px, py = sample_points_in_polygon(reef_geom, args.particles, seed=seed_val)
				# Diagnostics and shape validation
				px = np.asarray(px).reshape(-1)
				py = np.asarray(py).reshape(-1)
				depth_arr = np.zeros_like(px)
				if args.debug_particles:
					logging.info("[particles debug] counts lon=%d lat=%d depth=%d", px.size, py.size, depth_arr.size)
				if not (px.size == py.size == depth_arr.size):
					logging.error("Particle coordinate length mismatch lon=%d lat=%d depth=%d", px.size, py.size, depth_arr.size)
					return 12
				# Use from_list constructor for compatibility with installed Parcels version
				try:
					pset = ParticleSet.from_list(fieldset=fs, pclass=ReefParticle, lon=px.tolist(), lat=py.tolist(), depth=depth_arr.tolist())  # type: ignore
				except AttributeError:
					# Fallback to legacy constructor if from_list not present
					pset = ParticleSet(fieldset=fs, ptype=ReefParticle, lon=px.tolist(), lat=py.tolist(), depth=depth_arr.tolist())  # type: ignore
				if args.debug_particles:
					try:
						logging.info("[particles debug] ParticleSet size=%d", len(pset))  # type: ignore[arg-type]
					except Exception:  # noqa: BLE001
						pass
				if w_index == 0:
					logging.info("Injected %d particles (default fieldset start time used)", len(px))
				else:
					logging.warning("Multi-week timing not yet aligned with FieldSet time axis; subsequent weeks may need FieldSet rebuild for accurate timing.")
				# Kernels (wrap functions using pset.Kernel before combining)
				adv_kernel = pset.Kernel(AdvectionRK4)
				inside_kernel = pset.Kernel(SampleInside)
				base_kernel = adv_kernel + inside_kernel
				if args.kh > 0:
					diff_kernel = pset.Kernel(DiffusionUniformKh)
					base_kernel += diff_kernel  # Kh fields already added if kh>0
				if args.debug_particles:
					logging.info("[particles debug] Kernels composed kh>0=%s", str(args.kh > 0))
				# Execution parameters (single run writing ParticleFile)
				dt = 300  # 5 minutes
				outputdt = int(args.output_interval_hours * 3600)
				endtime = inj_time + np.timedelta64(args.runtime_days, 'D')
				def delete_out_of_bounds(particle, fieldset, time):  # type: ignore[no-untyped-def]
					particle.delete()
				try:
					from parcels import ParticleFile as ParcelsParticleFile  # type: ignore
				except ImportError:  # pragma: no cover
					logging.error("ParticleFile class missing")
					return 9
				pf_path = csv_dir / f"{_sanitize(gbr_name)}_{rid}_week{w_index:02d}_particles.nc"
				recovery_map = {
					getattr(ErrorCode, 'ErrorOutOfBounds', 'ErrorOutOfBounds'): delete_out_of_bounds,
					getattr(ErrorCode, 'ErrorThroughSurface', 'ErrorThroughSurface'): delete_out_of_bounds,
					getattr(ErrorCode, 'ErrorTimeExtrapolation', 'ErrorTimeExtrapolation'): delete_out_of_bounds,
				}
				# ParticleFile signature differs across Parcels versions.
				# Observed error shows our previous call treated second arg as particleset, so signature likely (name, particleset,...).
				# Try (name, particleset) ordering first; then keyword fallback; finally minimal new-style.
				pf = None
				try:
					pf = ParcelsParticleFile(str(pf_path), pset, outputdt=outputdt)  # legacy ordering (name, particleset)
				except RuntimeError as e:
					# NetCDF disabled in newer Parcels; switch to Zarr
					if 'Use .zarr extension' in str(e):
						pf_path = pf_path.with_suffix('.zarr')
						pf = ParcelsParticleFile(str(pf_path), pset, outputdt=outputdt)  # retry with zarr directory
					else:
						raise
				except TypeError:
					# Try keyword signature variants
					try:
						pf = ParcelsParticleFile(name=str(pf_path), particleset=pset, outputdt=outputdt)
					except (TypeError, RuntimeError) as e2:
						if isinstance(e2, RuntimeError) and 'Use .zarr extension' in str(e2):
							pf_path = pf_path.with_suffix('.zarr')
							pf = ParcelsParticleFile(name=str(pf_path), particleset=pset, outputdt=outputdt)
						else:
							pf = ParcelsParticleFile(name=str(pf_path), outputdt=outputdt)
				if args.debug_particles:
					logging.info("[particles debug] ParticleFile created path=%s class=%s", pf_path, type(pf).__name__)
				if args.debug_particles:
					logging.info("[particles debug] Using ParticleFile class %s", ParcelsParticleFile.__name__)
				# Execute simulation; adapt to API differences (some versions lack outputdt kw in execute)
				exec_kwargs = dict(
					dt=dt,
					endtime=endtime,
					particlefile=pf,
					recovery=recovery_map,
					verbose_progress=False,
				)
				try:
					pset.execute(base_kernel, outputdt=outputdt, **exec_kwargs)
				except TypeError as e:
					if 'outputdt' in str(e):
						if args.debug_particles:
							logging.info('[particles debug] execute() without outputdt retry due to signature mismatch')
						pset.execute(base_kernel, **exec_kwargs)
					else:
						raise
				if args.animate and w_index == 0:
					anim_path = csv_dir / f"{_sanitize(gbr_name)}_{rid}_week{w_index:02d}.mp4"
					try:
						animate_week(pf_path, reef_geom, anim_path, max_hours=168.0)
					except Exception as e:  # noqa: BLE001
						logging.warning("Animation error for %s %d week %d: %s", rid, year, w_index, e)
				# Load output
				# Open particle data (support NetCDF .nc or Zarr store)
				if pf_path.suffix == '.zarr' or pf_path.is_dir():
					try:
						ds = xr.open_zarr(pf_path)  # type: ignore[arg-type]
					except Exception as e:  # noqa: BLE001
						logging.error("Failed opening Zarr particle output %s: %s", pf_path, e)
						return 13
				else:
					try:
						ds = xr.open_dataset(pf_path)
					except Exception as e:  # noqa: BLE001
						logging.error("Failed opening NetCDF particle output %s: %s", pf_path, e)
						return 13
				inside_da = ds.get("inside")
				if inside_da is None:
					logging.error("inside variable missing in particle file for week %s", week_str)
					return 10
				# inside dims (obs, traj)
				obs_dim_name = inside_da.dims[0]
				traj_dim_name = inside_da.dims[1]
				initial_n = inside_da.sizes[traj_dim_name]
				times = ds["time"].values
				week_rows: list[dict] = []
				for obs_i in range(inside_da.sizes[obs_dim_name]):
					current_time = np.datetime64(times[obs_i])
					elapsed_h = (current_time - np.datetime64(times[0])).astype('timedelta64[s]').astype(float) / 3600.0
					inside_vals = inside_da.isel({obs_dim_name: obs_i}).values.astype(float)
					active_mask = ~np.isnan(inside_vals)
					particles_active = int(active_mask.sum())
					inside_count = int(np.nansum(inside_vals))
					frac_inside = inside_count / initial_n if initial_n > 0 else np.nan
					week_rows.append({
						"gbr_name": gbr_name,
						"label_id": rid,
						"year": year,
						"week_start": week_str,
						"hour_from_release": round(elapsed_h, 6),
						"particles_initial": initial_n,
						"particles_active": particles_active,
						"particles_inside": inside_count,
						"frac_inside": round(frac_inside, 6),
					})
				week_df = pd.DataFrame(week_rows)
				existing = pd.concat([existing, week_df], ignore_index=True)
				existing.to_csv(csv_path, index=False)
				logging.info("Week %s complete (%s %d) rows=%d", week_str, rid, year, len(week_df))
			total_fieldsets += 1
			if args.preview:
				break
		if args.preview:
			break

	logging.info("Simulation complete. Reef-year configurations processed: %d", total_fieldsets)
	return 0


if __name__ == "__main__":  # pragma: no cover
	raise SystemExit(main())