# Simulate the flows just before and after sampling.
# "18-096" Davies, "16-068" Thretford "18-032" Rib
ids = ["19-019"]                 # List of LABEL_ID reef identifiers         
years = [2023]                  # Either [YEAR] or list e.g. [2015,2016]
# Date periods use fixed 3-letter month + day (Jan01-Apr30). Multiple periods allowed.
date_periods = "Jul04-Jul11"    # Date range to download data. Sampling 07 July
model_name = "gbr1_2.0"         # Short model identifier for naming
depth_m = -2.35                 # Target depth (m, negative downward) uses nearest depth layer
buffer_km = 30
data_root = "working/03-data/eDNA"              # Directory containing extracted daily subcubes
traces_root = "C:/Temp/gis/ereefs-traces/eDNA"  # Directory to save particle simulation traces
plots_root = "working/07-plots/eDNA"
opendap_url = "https://thredds.nci.org.au/thredds/dodsC/fx3/model_data/gbr1_2.0.ncml"
dt_hours = 0.2                  # Integration timestep (hours)
runtime = 32                    # Optional max runtime (hours)
overwrite = false                # Overwrite existing outputs if true
num_particles = 50              # Number of particles to release each interval
injection_interval = 1          # (day) How often to run the particle tracer
random_seed = 1234              # Make the runs repeatable
kh_m2s = 0.25                   # Random dispersion m2/s. spread std = sqrt(2 kh Δt) 
                                # kh of 1 m2s ~ 85 m / hr